deployments:
  giropops-senhas:
    name: "giropops-senhas-helm"
    image: "linuxtips/giropops-senhas:1.0"
    replicas: 5
    ports:
      - port: 5000 # porta da aplicacao flask
        targetPort: 5000
        name: "giropops-senhas-port"
        serviceType: "NodePort"
        nodePort: 32500
      - port: 8088 # porta do prometheus expondo as metricas
        targetPort: 8088
        name: "giropops-senhas-metrics"
        serviceType: "ClusterIP"
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "0.25"
      limits:
        memory: "128Mi"
        cpu: "0.5"
  redis:
    name: "redis-helm" 
    image: "redis"
    ports:
      - port: 6379
        targetPort: 6379
        name: "redis-port"
        serviceType: "ClusterIP"
    replicas: 1
    labels:
      app: "redis"
      env: "labs"
      live: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "0.25"
      limits:
        memory: "128Mi"
        cpu: "0.5"
services:
  giropops-senhas:
    ports:
      - port: 5000 # porta da aplicacao flask
        targetPort: 5000
        name: "app"
        serviceType: "NodePort"
        nodePort: 32500
      - port: 8088 # porta do prometheus expondo as metricas
        targetPort: 8088
        name: "metrics"
        serviceType: "ClusterIP"
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"
  redis:
    ports:
      - port: 6379 # porta do redis
        targetPort: 6379
        name: "service"
        serviceType: "ClusterIP"
    labels:
      app: "redis"
      env: "labs"
      live: "true"
observability:
  giropops-senhas:
    logging: true      
    metrics:
      enable: true
      path: "/metrics"
databases:
  giropops-senhas:
    mysql:
      host: "mysql.svc.cluster.local"
      port: 3306
      name: "MyDB"

