# $component representa o giropopsSenhas e o redis no arquivo values.yaml referente ao campo deployment
# $config representa os campos que estiverem abaixo dos $component
{{- range $component, $config := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component }}
  labels:
    {{- include "app.labels" $config | nindent 4}} # 4 espacos no inicio da linha antes da primeira {
spec:
  replicas: {{ $config.replicas | default 2 }}
  selector:
    matchLabels:
      app: {{ $config.labels.app}}
  template:
    metadata:
      labels:
        {{- include "app.labels" $config | nindent 8 }} # 8 espacos no inicio da linha antes da primeira {
    spec:
      containers:
      - name: {{ $component }}
        image: {{ $config.image }}
        ports:
        {{- include "app.ports" $config | nindent 10 }}
        resources:
          {{- include "app.resources" $config | nindent 12 }}
---
{{- end }}


            



